# Generated by Django 5.1 on 2024-08-23 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_part',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='test_case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('output', models.CharField(max_length=100)),
                ('test_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.test_part')),
            ],
        ),
        migrations.CreateModel(
            name='variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.CharField(max_length=100)),
                ('input', models.CharField(max_length=100)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.test_case')),
            ],
        ),
    ]
